title: <p align="center">Jessie Le</p> # your name (or website title) here 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <p align="center">
  <a href="https://www.linkedin.com/in/jessie144/">LinkedIn</a> |    
  <a href="https://github.com/jessiehangle/jessiehangle.github.io/blob/master/pdf/Hang%20Le_Resume.pdf">Resume</a> | 
  <a href="https://github.com/jessiehangle">GitHub</a>
  </p>
  <br>
  <p align="justify">I am currently pursuing MS Degree in Business Analytics with Concentration in Statistics at Drexel University, Philadelphia. 
  <br>
  My specialization are statistical and econometric modeling, data mining, optimization algorithms, machine learning and natural language processing applied to finance, consulting, healthcare and manufacturing. 
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
