title: Jessie Le # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
I am currently pursuing MS Degree in Business Analytics with concentration in Statistic at Drexel University, Philadelphia. My specialization are statistical and econometric modeling, data mining, optimization algorithms, machine learning and natural language processing applied to finance, consulting, healthcare and manufacturing. 
  <br>
 
  <a href="https://www.linkedin.com/in/jessie144/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
